name: Build Flask-Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk libssl-dev libffi-dev build-essential python3-pip

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install buildozer cython

      - name: Set up Android SDK
        run: |
          # Create Android SDK directory
          mkdir -p $HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          
          # Download command line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/tools.zip
          unzip -q /tmp/tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          
          # Add to PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> $GITHUB_PATH
          
          # Set environment variables
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

      - name: Install Android packages with specific build-tools version
        run: |
          # Accept licenses first
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # Install specific versions that include Aidl
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "build-tools;30.0.3" \  # Version known to include Aidl
            "build-tools;34.0.0" \  # Latest version
            "platforms;android-34" \
            "ndk;25.2.9519653"

      - name: Verify Aidl installation
        run: |
          # Check if Aidl exists in any build-tools directory
          find $ANDROID_SDK_ROOT/build-tools -name "aidl" -type f | head -5
          
          # List available build-tools versions
          ls -la $ANDROID_SDK_ROOT/build-tools/ || echo "No build-tools directory"
          
          # Check specific versions
          if [ -f "$ANDROID_SDK_ROOT/build-tools/30.0.3/aidl" ]; then
            echo "Aidl found in build-tools 30.0.3"
            $ANDROID_SDK_ROOT/build-tools/30.0.3/aidl --version || echo "Aidl version check failed"
          fi
          
          if [ -f "$ANDROID_SDK_ROOT/build-tools/34.0.0/aidl" ]; then
            echo "Aidl found in build-tools 34.0.0"
            $ANDROID_SDK_ROOT/build-tools/34.0.0/aidl --version || echo "Aidl version check failed"
          fi

      - name: Set up Buildozer directories with correct paths
        run: |
          # Create the directory structure that Buildozer expects
          mkdir -p ~/.buildozer/android/platform/android-sdk
          
          # Link the actual SDK to where Buildozer expects it
          ln -sfn $ANDROID_SDK_ROOT ~/.buildozer/android/platform/android-sdk
          
          # Create the old tools directory structure that Buildozer looks for
          mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
          
          # Create a symlink for sdkmanager in the old location
          ln -sfn $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
          
          # Find and link NDK
          NDK_PATH=$(find $ANDROID_SDK_ROOT -name "ndk*" -type d | head -n 1)
          if [ -n "$NDK_PATH" ]; then
            echo "Linking NDK: $NDK_PATH"
            ln -sfn $NDK_PATH ~/.buildozer/android/platform/android-ndk
          else
            echo "Warning: NDK not found"
          fi

      - name: Create symlink for Aidl if missing
        run: |
          # Check if Aidl exists in any build-tools version and create symlink
          for version in "34.0.0" "30.0.3"; do
            if [ -f "$ANDROID_SDK_ROOT/build-tools/$version/aidl" ]; then
              echo "Found Aidl in build-tools $version"
              # Ensure the target directory exists
              mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools/$version/
              # Create symlink
              ln -sfn $ANDROID_SDK_ROOT/build-tools/$version/aidl ~/.buildozer/android/platform/android-sdk/build-tools/$version/aidl
              echo "Created symlink for Aidl from version $version"
              break
            fi
          done

      - name: Build with Buildozer
        run: |
          # Build the APK with verbose output
          buildozer -v android debug

      - name: List generated files for debugging
        run: |
          ls -la
          ls -la bin/ 2>/dev/null || echo "No bin directory found"
          find . -name "*.apk" -o -name "*.aab" 2>/dev/null | head -n 10 || echo "No APK files found"

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: flask-android-app
          path: bin/*.apk
          if-no-files-found: error