name: Build Flask Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDSDK: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
      ANDROIDNDK: ${{ github.workspace }}/.buildozer/android/platform/android-ndk-r25b
      ANDROIDAPI: 31
      ANDROIDMINAPI: 21
      PYTHON_VERSION: 3.10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip python3-venv \
            git openjdk-11-jdk \
            build-essential \
            libssl-dev zlib1g-dev \
            curl wget unzip

      - name: Set Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade buildozer Cython==0.29.36

      - name: Patch PyJNIus for Python 3
        run: |
          pip install --upgrade pyjnius==1.4.0
          # Optional: patch if needed
          PYJNIUS_DIR=$(python -c "import jnius; import os; print(os.path.dirname(jnius.__file__))")
          sed -i 's/isinstance(arg, long)/isinstance(arg, int)/g' $PYJNIUS_DIR/jnius_utils.pxi || true

      - name: Initialize Buildozer
        run: buildozer android clean

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: myflaskapp.apk
          path: bin/*.apk
